# Generated by Django 2.2.3 on 2019-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinessurl',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
