# Generated by Django 2.2.3 on 2019-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_appinessurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinessurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
