# Generated by Django 2.2.3 on 2019-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_appinessurl_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinessurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
