# Generated by Django 2.2.3 on 2019-07-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20190728_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinessurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
