# Generated by Django 2.2.3 on 2019-07-28 17:44

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_appinessurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinessurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
