# Generated by Django 2.2.3 on 2019-07-29 05:35

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0007_auto_20190728_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('appiness_URL', models.OneToOneField(on_delete=shortener.models.appinessURL, to='shortener.appinessURL')),
            ],
        ),
    ]
