# Generated by Django 2.2.3 on 2019-07-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='appiness_URL',
            field=models.OneToOneField(on_delete=None, to='shortener.appinessURL'),
        ),
    ]
